### ISSUE TITLE
pulling failed

### ISSUE THREAD

**Issue by hq9000** [nicklasfrahm/scp-action#10]
hello,

we have this action failing with the following error:

![image](https://user-images.githubusercontent.com/21345604/175032807-d4a681bd-2179-4185-8ab6-126b79b939c9.png)

config:
![image](https://user-images.githubusercontent.com/21345604/175033039-43058c61-466e-4b98-8a77-a96c9654b05f.png)

**Comment by nicklasfrahm** [comment]
@hq9000 Are you still experiencing this issue? I am able to pull the image without any issue and authentication.

What operating system and CPU architecture is your runner running on?

**Comment by hq9000** [comment]
nope, it resolved itself in 1h or so. thank you and apologies for bothering.

**Comment by nicklasfrahm** [comment]
No issue at all! :)
