### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by raphaelscholle** [nicklasfrahm/scp-action#11]
Hello, I've just started using your action, but there is a feature which would help me immensely.
Can you add a option to erase a file via scp ?
It would really help to decludder the fileserver. (In our usecase I would upload a new file and delete an older one, without directly overwriting it)

**Comment by aloxe** [comment]
You can find https://github.com/appleboy/scp-action that does that…

**Comment by nicklasfrahm** [comment]
@raphaelscholle can you describe your use-case a little more? Why are you not using an action that can execute SSH commands to do that?

**Comment by raphaelscholle** [comment]
Thanks for your answer, I've just changed my upload-workflow, to do it a little different.

When creating this issue, I wanted to push a generated artifact XYZ$DATE.zip to a server and wanted to erase a older version of said file.

It isn't needed anymore, since I changed from my own server to cloudflare, which has dedicated actions for that usecase.
If you want you can close the issue.
