### ISSUE TITLE
No option for passphrase

### ISSUE THREAD

**Issue by bjajoh** [nicklasfrahm/scp-action#4]
Am I understanding it correct that there is no option for a passphrase instead of ssh key?

**Comment by nicklasfrahm** [comment]
Yes, that is correct. I might be able to look into it today or tomorrow. 😊

My suggestion would be to add the following configuration parameters:

- [x] `insecure_password` is the password for the target
- [x] `insecure_proxy_password` is the password for the proxy

Additionally, it might be good to log a warning message indicating that this is insecure.

**Comment by bjajoh** [comment]
That would be really nice! :)
Your suggestion sounds good, exactly what I was looking for! 👍

**Comment by nicklasfrahm** [comment]
@bjajoh Could you check if the most recent version on the `main` branch works for you? If it does, I will create a new release. 🎉

**Comment by Briaker** [comment]
Can support for ssh passphrases be added with something like this? ~~I'd make a PR if I could~~ nm made one PR #6. Also I'm not familiar with GO, so the syntax may not be correct.
