### ISSUE TITLE
Add option to ignore fingerprint

### ISSUE THREAD

**Issue by nicklasfrahm** [nicklasfrahm/scp-action#5]
Currently it is required to provide a host fingerprint. Some users like to live dangerously, so lets add the following features:

- [x] `insecure_ignore_fingerprint` to ignore fingerprint verification on the target
- [x] `insecure_proxy_ignore_fingerprint` to ignore fingerprint verification on the proxy

In addition we should log a warning to indicate that this is insecure.

**Comment by bjajoh** [comment]
"Some users like to live dangerously" :+1: 
Actually the use case a local virtualized container which is used as a build system.
SCP would just be used in that local environment to get the build artifacts back.

**Comment by andrius** [comment]
It is not about danger, for example in my case I used it as a part of newly created digital ocean droplet bootstrap, it is fresh new server with initial ssh key and root access that script should process. 

As a workaround I used to update fingerprint, but it is an extra step, I wanted to save some resources: the whole workflow size is 50k characters.

**Comment by shwuhk** [comment]
May I know if fingerprint required now? Thanks

**Comment by nicklasfrahm** [comment]
@haidertm @andrius @shwuhk I added the requested functionality.

Could you test if it works for you by setting the action version in your workflow to `nicklasfrahm/scp-action@main`? If it does, I will create a new release.
